// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFHVg21b7emmJwXyWmjbv3ArRWsSGkDN0',
    appId: '1:382501328239:web:3aaa4dca633cbd481e049a',
    messagingSenderId: '382501328239',
    projectId: 'voxx-e8faf',
    authDomain: 'voxx-e8faf.firebaseapp.com',
    storageBucket: 'voxx-e8faf.appspot.com',
    measurementId: 'G-VC59QCZMJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1paqIpsnaThnREFNTcDhLFovQLIk6Vwg',
    appId: '1:382501328239:android:61cc9c0c548c9f381e049a',
    messagingSenderId: '382501328239',
    projectId: 'voxx-e8faf',
    storageBucket: 'voxx-e8faf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7KcIS1_9RXjU86FYqhDuexUCS8cTP0xQ',
    appId: '1:382501328239:ios:5b222ce5ff2204551e049a',
    messagingSenderId: '382501328239',
    projectId: 'voxx-e8faf',
    storageBucket: 'voxx-e8faf.appspot.com',
    iosBundleId: 'com.example.vox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7KcIS1_9RXjU86FYqhDuexUCS8cTP0xQ',
    appId: '1:382501328239:ios:a7a390ae8e34cd351e049a',
    messagingSenderId: '382501328239',
    projectId: 'voxx-e8faf',
    storageBucket: 'voxx-e8faf.appspot.com',
    iosBundleId: 'com.example.vox.RunnerTests',
  );
}
